[gobi]
recipes = [
    "list",
    "help",
    "shell",
    "project-manager",
    "cache",
]
child-recipes = [
    "list",
    "help",
    "shell",
]

[shell.hello]
command="""
    echo "hello world!"
"""
