[gobi]
recipes = [
    "list",
    "help",
    "shell",
    "project-manager",
]
child-recipes = [
    "list",
    "help",
    "shell",
]

[shell.hello]
command="""
    echo "hello world!"
"""

[gobi.projects]
carrot = "C:\\Users\\ibricchi\\Documents\\carrot\\gobi.ps1.toml"