def help_menu():
    print("gobi has two use modes:")
    print("gobi <command> <args>?")
    print("  command: the command to run (e.g. help for this menu)")
    print("  args: any arguments to pass to the command")
    print("gobi <project> <action> <args>?")
    print("  project: the project to run")
    print("  command: the command to run")
    print("  action: the action to run")
    print("  args: any arguments to pass to the action")
    exit(1)